#!/usr/bin/perl

use strict;
use warnings;
use 5.010;

use WebService::Pushover;
use Data::Dumper;

my $push = WebService::Pushover->new
    or die( "Unable to instantiate WebService::Pushover.\n" );
 
my %params = (
    token   => $ENV{PUSHOVER_APP},
    user    => $ENV{PUSHOVER_USER},
    title   => 'Pushover from Perl',
    message => shift || 'Test message',
);
 
say Dumper $push->message( %params );
